:white_check_mark: (CI/CD): Added deploy workflow #1022
COS-301/graduates pull request #1137
Opened 2022-04-18 21:47 UTC by brandon-c-k

close

2022-04-18 21:56 UTC, priyo5 requested changes
See comment made in file

2022-04-18 21:56 UTC, priyo5 commented on .github/workflows/deploy.yml
> +    branches: [ release ]
Add a wildcard to release to allow for multiple iterations of the branch see full.yml for reference

2022-04-18 22:06 UTC, brandon-c-k commented on .github/workflows/deploy.yml
> +    branches: [ release ]
@priyo5 noted

2022-04-19 08:28 UTC, arneschreuder commented
Closing, no more PRs to develop

2022-04-19 08:28 UTC, closed without merging