✨ 🤡 (Graphql): Mock api for student-profiles
COS-301/graduates pull request #189
Opened 2022-03-21 16:28 UTC by Xander-FP

Please advise on any changes.

2022-03-21 19:08 UTC, arneschreuder requested changes
Few small fixes, but mostly a near perfect PR. Thanks.

2022-03-21 19:08 UTC, arneschreuder commented on libs/api/student-profiles/api/shared/data-access/src/lib/student-profiles.module.ts
> +import { Module } from '@nestjs/common';
Since this is shared data access, this module will mostly just export modules.

2022-03-21 19:08 UTC, arneschreuder commented on libs/api/student-profiles/service/feature/src/index.ts
> +export * from './lib/student-api.service';
So this service feature lib should have a module that is exported here. Contain everything a person would need within the lib

2022-03-21 19:08 UTC, arneschreuder commented on libs/api/student-profiles/service/feature/src/index.ts
> +export * from './lib/student-api.service';
This is it: api-student-profiles-service-feature.module.ts

2022-03-21 19:08 UTC, arneschreuder commented on libs/api/student-profiles/service/feature/src/lib/student-api.service.ts
> +import { Student } from '@graduates/api/student-profiles/api/shared/data-access';
This is wrong. Service layer should not import from above. Student should be a model on the service layer. The API is responsible for converting from this type to their type.

2022-03-21 19:09 UTC, arneschreuder commented
Take note, PRs usually go hand in hand with some issue in the issue tracker/project board. So please link issues. You can then merge after changes have been made.

2022-03-21 21:20 UTC, Xander-FP commented on libs/api/student-profiles/api/shared/data-access/src/lib/student-profiles.module.ts
> +import { Module } from '@nestjs/common';
I am not entirely sure what to do here. Should I remove the import(and connected object) because it will not be used because in the future other modules will only be exported?

2022-03-22 07:55 UTC, arneschreuder commented on libs/api/student-profiles/api/shared/data-access/src/lib/student-profiles.module.ts
> +import { Module } from '@nestjs/common';
Yes, that is correct

2022-03-22 07:56 UTC, arneschreuder commented
Once you have resolved all of the requests. Then you can merge.

2022-03-22 20:21 UTC, Xander-FP commented on libs/api/student-profiles/service/feature/src/index.ts
> +export * from './lib/student-api.service';
I think I understand the concept, modules should get their services and export them such that other module can only import the module and use the exported services.
I proceeded to remove the export from "./lib/student-api.service" to fit this idea, but I cannot figure out how to import the exported StudentProfileService by only importing the service feature lib module into my api feature lib module.
Some guidance would be appreciated.

2022-03-23 08:02 UTC, arneschreuder commented on libs/api/student-profiles/service/feature/src/index.ts
> +export * from './lib/student-api.service';
So you are correct, you can not just import the module and then think the DI system will know where StudentProfileService comes from. So your service feature module has to export a FeatureModule that provides the services and exports it and then you also need to have an export like you have here: `export * from './lib/student-api.service';` so that other users can import both the FeatureModule (to be imported in their module) and the Service (for where they need to inject it)

2022-03-23 08:29 UTC, Xander-FP commented on libs/api/student-profiles/service/feature/src/index.ts
> +export * from './lib/student-api.service';
Thank you, I understand now.

2022-03-23 08:57 UTC, arneschreuder commented
Please update branch. PR is getting stale.

2022-03-23 11:23 UTC, arneschreuder commented
I would suggest you not merge to develop in your own branch first. This is fine, but can cause some issues for you with git. To keep it simple, you can just merge from directly from your feature branch. For now this is fine, Tests are failing though.

2022-03-23 11:37 UTC, arneschreuder approved these changes

2022-03-23 17:56 UTC, arneschreuder approved these changes

2022-03-23 18:10 UTC, merged

2022-03-23 19:26 UTC, Xander-FP commented on libs/api/student-profiles/service/feature/tsconfig.lib.json
> +    "composite": true
Initially, the tsconfig.json file threw an error there requesting that "composite": true should be added, but I thought removed it again in my final commit because removing it did not lead to that same error. I think the problem was fixed by closing and opening vscode because after I did that I have not gotten it again.