Companyrep
COS-301/graduates pull request #191
Opened 2022-03-21 22:05 UTC by Siphesihle05

⚓(Graphql): Added Company Rep profile Mock API

2022-03-22 07:42 UTC, arneschreuder requested changes
Thank you very much for the PR. Almost there. A few small fixes.

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/companyrep/api/feature/src/lib/companyrep.controller.ts
> +import { Controller, Get } from '@nestjs/common';
There are no controllers in the api. Just resolvers.

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/companyrep/api/feature/src/lib/companyrep.module.ts
> +import { CompanyrepService } from 'libs/api/companyrep/service/feature/src/lib/companyrep.service';
Please use this convention: `CompanyRepresentative` not `Companyrep`

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/companyrep/api/feature/src/lib/companyrep.module.ts
> +import { CompanyrepService } from 'libs/api/companyrep/service/feature/src/lib/companyrep.service';
Please use `@graduates/api/company-representative/....` as import.

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/companyrep/api/feature/src/lib/companyrep.module.ts
> +import { CompanyrepService } from 'libs/api/companyrep/service/feature/src/lib/companyrep.service';
This is technically incorrect. You should bundle the service in its own feature using its own feature module and them import that either directly in the shell or make a feature module for the entire company-representative feature that bundles the api and service and repository layer.

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/companyrep/api/feature/src/lib/companyrep.resolver.ts
> +    async addCompanyrep(@Args('newCompanyrepData') newCompanyrepData: NewCompanyrepInput,): Promise<Companyrep> {
Companyrep -> CompanyRepresentative and the API engineers need to standardise the conventions for create, fetch, delete and update

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/companyrep/api/shared/data-access/src/lib/companyrep.model.ts
> +@ObjectType({description: 'companeyrep profile'})
Please consult with the API engineers. The naming needs to be standardised. You can merge this in for now and fix later? But others have called this `*.entity.ts`

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/companyrep/api/shared/data-access/src/lib/new-companyrep.input.ts
> +    @Field(type => String)
This should technically be `type => ID` and force the types for the other fields as well please.

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/companyrep/api/shared/data-access/src/lib/new-companyrep.input.ts
> +import { Field, InputType } from '@nestjs/graphql';
Once again, I think the API engineers need to standardise here. I wouldve called this CreateCompanyRepresentativeRequest

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/companyrep/api/shared/data-access/src/lib/shared-data-access.module.ts
> +  providers: [NewCompanyrepInput, Companyrep],
Not sure if GraphQL types are listed as providers. Please check?

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/companyrep/service/feature/src/lib/companyrep.service.ts
> +import { Companyrep } from '../../../../api/shared/data-access/src/lib/companyrep.model';
Please use the '@graduates/path' import notation.

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/companyrep/service/feature/src/lib/companyrep.service.ts
> +import { Companyrep } from '../../../../api/shared/data-access/src/lib/companyrep.model';
Also, you never import a specific file. Only barrel the module and extract from that what you need.

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/companyrep/service/feature/src/lib/service-feature.module.ts
> +  providers: [CompanyrepService],
Naming convention

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/shell/feature/src/lib/api-shell-feature.module.ts
> +import { CompanyrepModule as ApiFeatureModule} from 'libs';
No, please call this something more descriptive. ApiCompanyRepApiFeatureModule similar to the others.

2022-03-22 07:42 UTC, arneschreuder commented on libs/api/shell/feature/src/lib/api-shell-feature.module.ts
> +      autoSchemaFile: 'schema.gql',
Perhaps just output this to a better location? Perhaps a library? There we can then generate interfaces from this graphql schema.

2022-03-22 07:42 UTC, arneschreuder commented on package.json
> +    "@nestjsi/class-validator": "^0.1.4",
Please notify the others that dependencies have been added. They need to yarn install again

2022-03-22 07:42 UTC, arneschreuder commented on tsconfig.base.json
> +      "@graduates/api\\companyrep\\api/data-acces": [
Slashes look odd. Please fix.

2022-03-22 07:42 UTC, arneschreuder commented on workspace.json
> +    "api\\companyrep\\api-feature": "libs/api/companyrep/api/feature",
Here as well.

2022-03-22 07:47 UTC, arneschreuder commented
Please tag your "feature project" on the meta together with the labels.

2022-03-22 07:52 UTC, arneschreuder commented
Also, changing a directory name like this: https://github.com/COS-301/graduates/pull/191/commits/7a9823621f0dc256c7a311922782ac8aec3a8b81 is not correct. You should use the nx console to rename projects. Directories are not just renamed. Please fix.

2022-03-22 11:28 UTC, arulagrawal submitted a review, later dismissed
I tried to look for issues and in some cases offered a quick fix. perhaps @arneschreuder should look at this as well since this is our first PR?

2022-03-22 11:29 UTC, arulagrawal commented
I just made that comment in the wrong tab :(. Is there anyway to delete?

2022-03-22 11:44 UTC, Siphesihle05 commented
> Also, changing a directory name like this: [7a98236](https://github.com/COS-301/graduates/commit/7a9823621f0dc256c7a311922782ac8aec3a8b81) is not correct. You should use the nx console to rename projects. Directories are not just renamed. Please fix.

I am using the the move commad in nx Console is that okay?

2022-03-22 11:56 UTC, arneschreuder commented
> > Also, changing a directory name like this: [7a98236](https://github.com/COS-301/graduates/commit/7a9823621f0dc256c7a311922782ac8aec3a8b81) is not correct. You should use the nx console to rename projects. Directories are not just renamed. Please fix.
> 
> I am using the the move commad in nx Console is that okay?

If that is the case, then yes, it just looked weird in the PR. If you are doing this go ahead.

2022-03-23 08:57 UTC, arneschreuder commented
Please resolve conflicts and update branch. This PR is getting stale.

2022-03-23 10:23 UTC, closed without merging