Check status
COS-301/graduates pull request #217
Opened 2022-03-22 10:36 UTC by MichaelDuPlessis

Code for a mock API was created, it for now just returns constant data and as of yet may no work if a mutation is used.

2022-03-22 11:29 UTC, arulagrawal requested changes
Added some comments and potential fixes. Perhaps @arneschreuder can help us out by looking at this also since this is our first PR?

2022-03-22 11:29 UTC, arulagrawal commented on libs/api/access-status/api/feature/src/lib/api-access-status.entity.ts
> +    accessStatus: string;
```suggestion
    @Field()
    userID!: string;

    @Field()
    item!: string;

    @Field()
    accessStatus: string;
```
I think the class member variables should all follow camelCase

2022-03-22 11:29 UTC, arulagrawal commented on libs/api/access-status/api/feature/src/lib/api-access-status.module.ts
> +import { ApiAccessStatusService } from './api-access-status.service';
We should use the '@graduates/path' import notation

2022-03-22 11:29 UTC, arulagrawal commented on libs/api/access-status/api/feature/src/lib/api-access-status.resolver.ts
> +import { ApiAccessStatusService } from "./api-access-status.service";
We should use the '@graduates/path' import notation

2022-03-22 11:29 UTC, arulagrawal commented on libs/api/access-status/api/feature/src/lib/api-access-status.service.ts
> +import { ApiAccessStatusEntity } from "./api-access-status.entity";
We should use the '@graduates/path' import notation

2022-03-22 11:29 UTC, arulagrawal commented on libs/api/shell/feature/src/lib/api-shell-feature.module.ts
> +import { ApiAccessStatusApiFeatureModule } from '@graduates/api/access-status/api//feature';
```suggestion
import { ApiAccessStatusApiFeatureModule } from '@graduates/api/access-status/api/feature';
```
I think the double '//' is probably not intended

2022-03-22 11:34 UTC, arulagrawal commented
I think the name of this PR should also follow the gitmoji standard. Something like 🤡(request-for-access): mock check status.

Note: not sure if this should be 🤡 or ✨

2022-03-22 11:44 UTC, MichaelDuPlessis commented on libs/api/access-status/api/feature/src/lib/api-access-status.service.ts
> +import { ApiAccessStatusEntity } from "./api-access-status.entity";
Could you explain please I am a bit unsure by what that is?

2022-03-22 11:46 UTC, MichaelDuPlessis commented on libs/api/access-status/api/feature/src/lib/api-access-status.entity.ts
> +    accessStatus: string;
This is correct thank you.

2022-03-22 11:48 UTC, arneschreuder commented on libs/api/access-status/api/feature/src/lib/api-access-status.resolver.ts
> +import { ApiAccessStatusService } from "./api-access-status.service";
Not in this case, since this is just internal. `@graduates/path` is used for "other libraries"

2022-03-22 11:48 UTC, arneschreuder commented on libs/api/access-status/api/feature/src/lib/api-access-status.module.ts
> +import { ApiAccessStatusService } from './api-access-status.service';
Not in this case, since this is just internal. `@graduates/path` is used for "other libraries"

2022-03-22 11:51 UTC, MichaelDuPlessis commented on libs/api/shell/feature/src/lib/api-shell-feature.module.ts
> +import { ApiAccessStatusApiFeatureModule } from '@graduates/api/access-status/api//feature';
Im looking into it as it was automatically done by vscode and it seems to create problems if it is a single slash

2022-03-22 11:52 UTC, arneschreuder requested changes
Small changes. If you made these, please go ahead and merge. Good job.

2022-03-22 11:52 UTC, arneschreuder commented on libs/api/access-status/api/feature/src/lib/api-access-status.entity.ts
> +    @Field()
please add @Field(type => ID)

2022-03-22 11:52 UTC, arneschreuder commented on libs/api/access-status/api/feature/src/lib/api-access-status.module.ts
> +  providers: [ApiAccessStatusResolver, ApiAccessStatusService],
This technically wrong. The ApiAccessStatusService should be in the libs/api/access-status/service/feature. Bundle that in a module and that module together with this one can either be bundled into a higher order library module or just import them directly in the shell.

2022-03-22 11:52 UTC, arneschreuder commented on libs/api/access-status/api/feature/src/lib/api-access-status.resolver.ts
> +    constructor(private accessStatusService: ApiAccessStatusService) {}
So this is fine yes, since you are injecting the service. The comment above refers to the module that bundles this service for others to use.

2022-03-22 11:53 UTC, arneschreuder commented
Please link this PR to related tasks in the issue tracker and project board.

2022-03-22 11:56 UTC, MichaelDuPlessis commented on libs/api/access-status/api/feature/src/lib/api-access-status.resolver.ts
> +    constructor(private accessStatusService: ApiAccessStatusService) {}
Just to clarify then, I should not move the service to libs/api/access-status/service/feature?

2022-03-22 12:09 UTC, arneschreuder approved these changes
Shipit!

2022-03-22 12:10 UTC, arneschreuder submitted a review, later dismissed

2022-03-22 12:14 UTC, arulagrawal commented on libs/api/shell/feature/src/lib/api-shell-feature.module.ts
> +import { ApiAccessStatusApiFeatureModule } from '@graduates/api/access-status/api//feature';
Semantically they should be equivalent... 
Perhaps if its causing issues we should leave it be? @arneschreuder 
I just thought it looked weird.

2022-03-22 13:04 UTC, arneschreuder commented on libs/api/shell/feature/src/lib/api-shell-feature.module.ts
> +import { ApiAccessStatusApiFeatureModule } from '@graduates/api/access-status/api//feature';
Nah, the double slashes cant be right.

2022-03-23 06:41 UTC, MichaelDuPlessis commented
@BenjaminOsmers and @MuziwandileTNdlovu your code is causing mine and most likely other peoples builds to fail could you please look at the errors and fix the problems.

2022-03-23 06:47 UTC, BenjaminOsmers commented
@MichaelDuPlessis Can you please elaborate?

2022-03-23 08:04 UTC, arulagrawal approved these changes

2022-03-23 08:12 UTC, arneschreuder commented
@MichaelDuPlessis @BenjaminOsmers @MuziwandileTNdlovu don't worry. I am fixing it.

2022-03-23 08:20 UTC, MuziwandileTNdlovu commented
> @MichaelDuPlessis @BenjaminOsmers @MuziwandileTNdlovu don't worry. I am fixing it.

@arneschreuder so we should wait ??

2022-03-23 08:24 UTC, BenjaminOsmers commented
How should we procceed?

2022-03-23 08:34 UTC, arulagrawal commented
I'm not sure how to run the checks without running the removed test-all check. Perhaps this PR can be merged anyway since the failing check has been removed? @BenjaminOsmers @arneschreuder

2022-03-23 08:34 UTC, MuziwandileTNdlovu commented
> How should we procceed?

I think we should just wait I had fixed the things on my fork i was about pull and see it it helps but he said we should not worry so lets just wait

2022-03-23 08:52 UTC, arneschreuder commented
@MichaelDuPlessis you can go ahead, pull from upstream develop into your feature branch, push feature branch again and let the pipeline run again. If it passes, please merge.

2022-03-23 10:19 UTC, arulagrawal approved these changes
I think this was the root cause of the double slash issue

2022-03-23 10:23 UTC, merged