💄(styling): added global color pallete
COS-301/graduates pull request #308
Opened 2022-03-23 21:26 UTC by Ruben-Brits

Implemented a global colour pallet for use throughout the UI. Also did a small UI change to ensure it works as inteded

2022-03-24 04:09 UTC, arneschreuder requested changes
Move assets please

2022-03-24 04:09 UTC, arneschreuder commented on apps/client/src/styles.scss
> +$primary-1 : #174372;
This file should be put into an assets folder, and probably be made into a shared lib?

2022-03-24 04:10 UTC, arneschreuder commented
Build is failing. Please fix issues in ci/cd and then we can get this merged in after you moved the assets

2022-03-30 18:30 UTC, Ruben-Brits commented on apps/client/src/styles.scss
> +$primary-1 : #174372;
moved into a shared asset lib

2022-03-31 07:35 UTC, dylan2894 approved these changes
Looks good 👍

2022-03-31 20:49 UTC, arneschreuder commented
Please add meta (labels, project, milestone etc) to the PR. Then merge.

2022-04-01 06:04 UTC, merged