Dockerfile Merge
COS-301/graduates pull request #348
Opened 2022-03-25 08:35 UTC by MichaelViljoen

Merging two dockerfiles and editing docker compose to include said dockerfiles

2022-03-26 07:40 UTC, KyleSmith19091 reviewed
Looks good

2022-03-26 15:11 UTC, KyleSmith19091 approved these changes

2022-03-31 20:20 UTC, arneschreuder requested changes
See comments please

2022-03-31 20:20 UTC, arneschreuder commented on apps/api/Dockerfile
> +ENV PORT=5433
Why this port?

2022-03-31 20:20 UTC, arneschreuder commented on apps/api/Dockerfile
> +EXPOSE 5433
`EXPOSE ${PORT}?` Since you are setting the variable in ENV

2022-03-31 20:20 UTC, arneschreuder commented on apps/client/Dockerfile
> +# Base Image
Although I totally get the Dockerfile for the client. This is usually not justified since the built-client will probably be less than 10 mb. So to host the client in a Dockerfile is very very much overkill. That being said, it does depend on how the client is going to be hosted. If you do choose to still host it in a Docker container, then technically the Nginx image is the correct one to use.

2022-03-31 20:20 UTC, arneschreuder commented on apps/client/Dockerfile
> +# Base Image
Consider

2022-03-31 20:20 UTC, arneschreuder commented on docker-compose.yml
> +      - "5433:5433"
Why this port?

2022-03-31 20:20 UTC, arneschreuder commented on docker-compose.yml
> +    links:
You define networks, but done add any of the services to them?

2022-03-31 20:20 UTC, arneschreuder commented on docker-compose.yml
> +
Also, why? Adding the api and the client to docker compose is not smart (unless it is part of some deployment process which should anyway then be docker-compose.dev.yml and is usually not included in the repo as it could contain keys etc.)

Think about it. Docker compose is to get services up and running.  Since this is a Node-based repo. There is no need for this, since everything you need is local. By doing this, you need to sync and mount your source files inside of the container and that adds like 2GB of memory. For what? Perhaps consider not doing this. The docker compose file was put there so you can quickly spin up postgres and that is pretty much where it ends.

2022-03-31 20:21 UTC, arneschreuder commented
Please update PR title to reflect the same style as the others.

2022-04-03 19:25 UTC, MichaelViljoen commented on apps/api/Dockerfile
> +ENV PORT=5433
I noticed on the docker file that was created for the prisma, the port 5432 was used, and I thought it would be appropriate to use the next port, are there recommended ports for dockerfiles, or would you prefer us to use any other specific ports.

2022-04-03 19:27 UTC, MichaelViljoen commented on apps/api/Dockerfile
> +ENV PORT=5433
@arneschreuder I noticed on the docker file that was created for the prisma, the port 5432 was used, and I thought it would be appropriate to use the next port, are there recommended ports for dockerfiles, or would you prefer us to use any other specific ports

2022-04-03 19:27 UTC, MichaelViljoen commented on apps/client/Dockerfile
> +# Base Image
@arneschreuder would it be appropriate to create the docker file so that there is an option to use it if needed.

2022-04-03 19:28 UTC, MichaelViljoen commented on docker-compose.yml
> +    links:
I will remove the defined network

2022-04-03 19:30 UTC, MichaelViljoen commented on docker-compose.yml
> +
@arneschreuder 
I will undo the changes to the dockercompose file, would you like my team to start working on a docker-compose.dev.yml file?

2022-04-03 19:42 UTC, MichaelViljoen commented on docker-compose.yml
> +
I have undone the changes made to the Docker Compose within this pull request.

2022-04-03 19:42 UTC, MichaelViljoen commented on docker-compose.yml
> +
I have undone the changes to the docker compose file.

2022-04-03 22:23 UTC, arneschreuder commented on docker-compose.yml
> +    links:
Actually, I mean, don’t remove the defined network. Just add it to the api service. The api and db needs to have the same network. The client doesn’t really care since it needs a fqdn for the api anyway.

2022-04-05 08:39 UTC, arneschreuder commented on apps/api/Dockerfile
> +ENV PORT=5433
Please keep it at 3333

2022-04-05 08:40 UTC, arneschreuder commented on apps/client/Dockerfile
> +# Base Image
Sure. Then just make sure it is the nginx one

2022-04-05 08:41 UTC, arneschreuder commented on docker-compose.yml
> +
@MichaelViljoen contact the delivery team. Ask them how they want to deploy the docker containers. With compose or a script? Then take it from there. If they use compose, then yes, make a .dev and .prod.yml

2022-04-05 14:57 UTC, MichaelViljoen commented on docker-compose.yml
> +      - "5433:5433"
This part of the Docker file has now been removed, but if it were to stay should it have been 3333

2022-04-05 14:59 UTC, MichaelViljoen commented on docker-compose.yml
> +
@arneschreuder I am currently in talks with them, as this file is in its orginal condition ( pre my merge) can i consider this issue resolved for now so that the rest of the merge can move forward?

2022-04-06 11:12 UTC, arneschreuder requested changes

2022-04-06 11:12 UTC, arneschreuder commented on apps/client/Dockerfile
> +# Base Image
Just this last file to either be removed or changed to nginx, then we can merge this in.

2022-04-10 17:49 UTC, arneschreuder commented
I'm copy pasting this on all the open PRs. Ignore if already seen or applied: https://github.com/COS-301/graduates/discussions/3?sort=new#discussioncomment-2540319

2022-04-10 17:49 UTC, arneschreuder commented
This PR is getting stale as well. Please resolve or we will close it.

2022-04-10 20:27 UTC, MichaelViljoen commented
> This PR is getting stale as well. Please resolve or we will close it.

2022-04-11 09:42 UTC, MichaelViljoen commented on apps/client/Dockerfile
> +# Base Image
I would like to add the file as is for the release, and work work on it going nginx for a future release.

2022-04-11 10:33 UTC, arneschreuder commented on apps/client/Dockerfile
> +# Base Image
Please dont. It is wrong. So I would rather have it correct than poluting the repo

2022-04-11 11:09 UTC, closed without merging