📦 (packages): added basic scripts
COS-301/graduates pull request #401
Opened 2022-03-30 21:24 UTC by FaraiQC

(packages): added basic scripts to the services folder of access-status

2022-03-31 17:25 UTC, arulagrawal requested changes
There are some things I'm unsure about, please clarify these if you can.
This PR is pretty big. It has changes to /doc /libs/api/access-status and /lib/api/request-access. Like I said in one of the comments I'm not sure the /doc part fits in this PR?

@arneschreuder should you please look at this PR?

2022-03-31 17:25 UTC, arulagrawal commented on changelog.html
> +<li>%h %ci %d %s</li>
I'm not too familiar with what scripts you're adding. Why is there a changeling.html in the root of the project with these contents?

2022-03-31 17:25 UTC, arulagrawal commented on yarn.lock
> -
Why are we messing with the lock file? I think we shouldn't be doing this. @arneschreuder

2022-03-31 17:25 UTC, arulagrawal commented on yarn.lock
> -"@nrwl/cli@13.9.4", "@nrwl/cli@^13.9.4":
Not sure what's going on here, but see other comment on this file

2022-03-31 17:25 UTC, arulagrawal commented on doc/doc-filelist.js
> +var tree={};
Judging by the PR message, this doc folder and its files aren't meant to be in this PR?

2022-03-31 17:25 UTC, arulagrawal commented on libs/api/access-status/shared/feature/README.md
> +# api-access-status-shared-feature
I'm not sure about the /shared path of these files. What is shared/feature doing?

2022-03-31 17:27 UTC, arulagrawal commented
These changes aren't 📦️ packages, please update the PR title and commit messages.

2022-03-31 17:45 UTC, FaraiQC commented on libs/api/access-status/shared/feature/README.md
> +# api-access-status-shared-feature
The /shared path should not be there. I only notice now that I put it there.

2022-03-31 17:51 UTC, FaraiQC commented on changelog.html
> +<li>%h %ci %d %s</li>
I ran this command "nx g @nrwl/nest:lib api/access-status/service/feature"  on the terminal in order to generate the services subfolder of my feature. The folder structure generated by this command is the same as that made by other service engineers.

2022-03-31 17:53 UTC, arulagrawal commented on changelog.html
> +<li>%h %ci %d %s</li>
Okay but what does this have to do with a changelog.html with gibberish in the root?

2022-03-31 17:59 UTC, arulagrawal commented
Could you please expand the PR description? Basic scripts to do what? What do you mean scripts? What feature are you adding? What are we adding to access-status in this PR?

2022-03-31 18:00 UTC, FaraiQC commented on yarn.lock
> -
I am not sure why there are changes made to this file. Could it have something to do with this command that I ran on the terminal "nx g @nrwl/nest:lib api/access-status/service/feature"?

2022-03-31 18:03 UTC, FaraiQC commented on yarn.lock
> -"@nrwl/cli@13.9.4", "@nrwl/cli@^13.9.4":
I am not sure why there are changes made to this file. Could it have something to do with this command that I ran on the terminal "nx g @nrwl/nest:lib api/access-status/service/feature"?

2022-03-31 18:14 UTC, FaraiQC commented
> Could you please expand the PR description? Basic scripts to do what? What do you mean scripts? What feature are you adding? What are we adding to access-status in this PR?

These scripts were added by me using this command "nx g @nrwl/nest:lib api/access-status/service/feature" in order to match the example folder structure given to us. What do you suggest I name this pull request message (instead of "[(packages): added basic scripts]")

2022-03-31 18:43 UTC, FaraiQC commented
I closed the PR because some tests started failing when I removed the shared folder (that should not have been there)

2022-03-31 19:32 UTC, FaraiQC commented on libs/api/access-status/shared/feature/README.md
> +# api-access-status-shared-feature
I removed the shared folder

2022-03-31 20:03 UTC, arneschreuder commented on changelog.html
> +<li>%h %ci %d %s</li>
I agree with arulagrawal. Also, you probably want to use the nx console plugin in VSCode to generate these. The command line works fine, but the parameters are a bit uncertain in you use the cli.

2022-04-01 07:44 UTC, FaraiQC commented on doc/doc-script.js
> +// # res/script.js
let me remove the doc folder

2022-04-01 07:55 UTC, FaraiQC reviewed
I removed the files that should not have been in the PR (the doc folder).

2022-04-01 08:08 UTC, arneschreuder commented
Tests pass. Resolve all conversations and then you can merge

2022-04-01 08:20 UTC, arulagrawal requested changes
Still need to remove changelog and agree on yarn.lock

2022-04-01 08:20 UTC, arulagrawal commented on changelog.html
> +<li>%h %ci %d %s</li>
This is not resolved, this file is still present

2022-04-01 08:20 UTC, arulagrawal commented on yarn.lock
> -
I think we should still try to leave this alone. As per @arneschreuder's comment, no package.json is strange

2022-04-01 10:31 UTC, FaraiQC commented on changelog.html
> +<li>%h %ci %d %s</li>
I just removed the changelog file as requested

2022-04-01 10:34 UTC, arneschreuder approved these changes
LGTM

2022-04-01 10:34 UTC, arulagrawal approved these changes

2022-04-01 10:35 UTC, arulagrawal commented
🚀

2022-04-01 10:35 UTC, merged