✨(GraphQL): Adding Mock API (Authentication)
COS-301/graduates pull request #405
Opened 2022-03-31 13:07 UTC by MoeMoola3

Adding the Mock API. Returns hardcoded data to get the API up and running.

2022-03-31 15:05 UTC, tshegomotlatle approved these changes
Looks good to me, doesn't break the pipeline and passes all tests provided by the CI/CD team

2022-03-31 20:48 UTC, arneschreuder requested changes
Few small changes, if that is fixed, then please go ahead and merge.

2022-03-31 20:48 UTC, arneschreuder commented on libs/api/authentication/api/feature/src/lib/api-authentication-api-feature.controller.specs.ts
> +import { AppController } from './api-authentication-api-feature.controller';
GraphQL using nest technically has a controller, but it is hidden underneath the plumbing of the @nestjs/graphql package.

2022-03-31 20:48 UTC, arneschreuder commented on libs/api/authentication/api/feature/src/lib/api-authentication-api-feature.controller.ts
> +import { Controller, Get } from '@nestjs/common';
Please remove this file. There are no controllers in the API.

2022-03-31 20:48 UTC, arneschreuder commented on libs/api/authentication/api/feature/src/lib/main.ts
> +import { NestFactory } from '@nestjs/core';
No. Please remove. No main files in the libs. The executable that bundle the app is in `apps/api`.

2022-03-31 20:48 UTC, arneschreuder commented on libs/api/authentication/api/feature/src/lib/users/users.entity.ts
> +    @Field(type => Int)
Or documentation for database.

2022-03-31 20:48 UTC, arneschreuder commented on libs/api/authentication/api/feature/src/lib/users/users.module.ts
> +  providers: [UsersService, UsersResolver]
Services should move to service layer in `libs/api/authentication/service/feature`. Then import using `@graduates/api/authentication/service/feature`

2022-03-31 20:48 UTC, arneschreuder commented on libs/api/authentication/api/feature/src/lib/users/users.service.ts
> +import { Injectable } from '@nestjs/common';
See other comments. Services should be in service layer.

2022-04-03 08:52 UTC, tshegomotlatle approved these changes
All the changes mentioned by Arne seem to be done. I'll authorize the merge to the develop branch

2022-04-03 09:19 UTC, merged