Authorization api
COS-301/graduates pull request #406
Opened 2022-03-31 13:42 UTC by Kuda214

✨🤡 (graphql) Added new Mock API and service

2022-03-31 21:09 UTC, arneschreuder commented
Please add meta such as labels, milestone, project, linked issues etc to this PR.

2022-03-31 21:14 UTC, arneschreuder requested changes
This PR is almost ready. Please see comments and get this badboy in.

2022-03-31 21:14 UTC, arneschreuder commented on .env
> +DATABASE_URL="postgresql://graduates:graduates@localhost:5432/?schema=public"
Why?

2022-03-31 21:14 UTC, arneschreuder commented on .env
> +DATABASE_URL="postgresql://graduates:graduates@localhost:5432/?schema=public"
Also, perhaps the DB should be called graduates? so then ...:5432/graduates?schema=public

2022-03-31 21:14 UTC, arneschreuder commented on libs/api/authorization/api/feature/src/index.ts
> +export * from './lib/api-authorization.resolver'
Why? Nobody else is going to import the resolver?

2022-03-31 21:14 UTC, arneschreuder commented on migrations.json
> +{
What is this file? And why is it changed?

2022-03-31 21:14 UTC, arneschreuder commented on package.json
> +    "@nrwl/angular": "13.9.5",
Nothing to resolve here. Just a comment. Updating packages should be done very carefully and is usually done by a single repo admin. These are fine since all of them are minor and patch updates. But just keep this in mind ok :)

2022-04-01 08:43 UTC, Kuda214 commented
> Please add meta such as labels, milestone, project, linked issues etc to this PR.

okay will do

2022-04-01 08:44 UTC, Kuda214 commented on package.json
> +    "@nrwl/angular": "13.9.5",
okay

2022-04-01 08:44 UTC, Kuda214 commented on migrations.json
> +{
I was trying to let my code pass the test by fixing the test error

2022-04-01 08:45 UTC, Kuda214 commented on libs/api/authorization/api/feature/src/index.ts
> +export * from './lib/api-authorization.resolver'
Noted I will remove that

2022-04-01 08:45 UTC, Kuda214 commented on .env
> +DATABASE_URL="postgresql://graduates:graduates@localhost:5432/?schema=public"
I was getting an error, mydb does not exist

2022-04-01 08:47 UTC, Kuda214 commented on .env
> +DATABASE_URL="postgresql://graduates:graduates@localhost:5432/?schema=public"
will change it to graduates

2022-04-01 08:50 UTC, Kuda214 commented on migrations.json
> +{
had it deleted

2022-04-02 09:45 UTC, Ray-net submitted a review, later dismissed
All main patch updates are minor patches and thus will not result in an over haul of the but please dont try to update the packages in future PR's. All api files seems in order.

2022-04-02 12:33 UTC, Vhulenda88 submitted a review, later dismissed

2022-04-02 12:36 UTC, Vhulenda88 reviewed
Will the changes of versions in the yarn.lock not affect anything

2022-04-02 15:10 UTC, Kuda214 commented
> Will the changes of versions in the yarn.lock not affect anything

no these files wont affect anything

2022-04-03 05:09 UTC, arneschreuder requested changes
Just resolve conflicts then you can merge

2022-04-03 05:09 UTC, arneschreuder commented
I always just chuck away yarn.lock and regenerate it again using yarn install

2022-04-03 22:45 UTC, Vhulenda88 commented
There were some changes made to the CI tests, which is making your PR fail to merge, please add:
Exactly 1 of each is required:

Priority,type,status

Minimum of 1 for:
role and scope

Milestone required.

With regards to Meta 
data for PRs. You can let your groups know

Violation of above rules leads to PR failure.

~CI/CD Team

2022-04-04 06:48 UTC, Kuda214 commented
@arneschreuder It  looks like the test is failing because of another feature's test "notifications feature" ? Is that it or there something I need to fix on my side

2022-04-04 07:03 UTC, Ray-net reviewed
did the notification team change the apps/api/project.json file?

2022-04-04 07:19 UTC, Kuda214 commented
l am not too sure

2022-04-06 11:14 UTC, arneschreuder commented
Hi There. Can I ask that you please update your branch with latest in upstream development and resolve conflicts. Then we see if the CI still fails.

2022-04-06 11:50 UTC, closed without merging