💄(ui): Added admin console feature UI files
COS-301/graduates pull request #466
Opened 2022-04-04 11:06 UTC by bevanslabbert

Generated feature library in libs/client and angular component in libs/client/adminconsole/feature/src/lib.

2022-04-04 16:56 UTC, KayleePosthumus commented on apps/client/src/app/app.component.html
> +<graduates-adminconsole></graduates-adminconsole>
Is there a reason this is changed?

2022-04-04 16:59 UTC, KayleePosthumus approved these changes

2022-04-04 17:00 UTC, KayleePosthumus commented
@bevanslabbert after you have fixed the conflicts this PR is good to go

2022-04-05 04:30 UTC, KayleePosthumus approved these changes

2022-04-05 04:32 UTC, KayleePosthumus commented
@bevanslabbert find out with CI/CD why some of the tests fail and if you can resolve them.

2022-04-05 04:41 UTC, Alexander-Muendesi commented
![image](https://user-images.githubusercontent.com/93581519/161679896-0e4f1101-ff6a-413d-9d57-bb0dbdb4676d.png)
@KayleePosthumus @bevanslabbert it seems as though the changes you made to fix those initial conflicts are the reason it is failing

2022-04-05 04:48 UTC, Alexander-Muendesi commented
And I think more specifically its to do with changes to the package-lock.json but I am not 100% sure

2022-04-05 07:01 UTC, KayleePosthumus commented
@Alexander-Muendesi , @bevanslabbert reverted the file, is there any other reason this might still fail or can we merge?

2022-04-05 07:02 UTC, KayleePosthumus approved these changes

2022-04-05 07:38 UTC, Alexander-Muendesi commented
Consulting with CI/CD team on the issue. Will update if any solutions are proposed to your problem

2022-04-05 08:42 UTC, arneschreuder commented
Please resolve conflicts.

2022-04-05 09:06 UTC, KayleePosthumus submitted a review, later dismissed

2022-04-05 09:11 UTC, KayleePosthumus commented
@arneschreuder the conflicts are fixed, do you have any idea why it is failing the checks, me and a member of CI/CD are stuck?

2022-04-05 09:18 UTC, arneschreuder commented
Lets clear CI/CD cache

2022-04-05 09:20 UTC, arneschreuder commented
I suggest closing the PR and then making the PR from a feature branch. Trying to merge fork:develop to upstream:develop can sometimes be tricky.

2022-04-05 09:21 UTC, arneschreuder commented
Yeah, the above should def help. @bevanslabbert You need to sync you dev branch with upstream. It is not right.

2022-04-05 15:43 UTC, KayleePosthumus commented
@bevanslabbert please follow what arne has said

2022-04-10 17:49 UTC, arneschreuder commented
I'm copy pasting this on all the open PRs. Ignore if already seen or applied: https://github.com/COS-301/graduates/discussions/3?sort=new#discussioncomment-2540319

2022-04-10 18:07 UTC, arneschreuder commented
Please update with `upstream/develop` and make the PR from a feature branch, not directly from your develop. It makes it difficult for you if issues occur.

2022-04-10 18:14 UTC, arneschreuder requested changes
Please do not use npm. Use yarn. Remove package-lock.json. This should also be gitignored.

2022-04-10 18:14 UTC, arneschreuder commented on apps/client/src/app/app.module.ts
> +import { ClientAdminconsoleFeatureModule as AdminConsole } from '@graduates/client/adminconsole/feature';
No, this is wrong. Your feature should be lazy loading using angular routing. https://angular.io/guide/lazy-loading-ngmodules

2022-04-10 18:14 UTC, arneschreuder commented on libs/client/adminconsole/feature/src/lib/adminconsole/adminconsole.component.spec.ts
> +describe('AdminconsoleComponent', () => {
Needs a LOT more testing.

2022-04-10 18:14 UTC, arneschreuder commented on libs/client/adminconsole/feature/src/lib/adminconsole/adminconsole.component.ts
> +  burger : boolean
This is fine for now. But please make use of a store to do state and data management for your feature. https://www.ngxs.io.

2022-04-10 18:14 UTC, arneschreuder commented on libs/client/adminconsole/feature/src/lib/client-adminconsole-feature.module.spec.ts
> +  // TODO: Add real tests here.
Yes, I agree :)

2022-04-10 18:14 UTC, arneschreuder commented on libs/client/adminconsole/feature/src/lib/client-adminconsole-feature.module.ts
> +  imports: [CommonModule],
So this module must import from a `client-adminconsole-feature.routing-module.ts` which does the lazy loading for this feature.

2022-04-10 18:14 UTC, arneschreuder commented on package.json
> +}
Please chuck this away in your PR.

2022-04-10 18:14 UTC, arneschreuder commented on tsconfig.base.json
> +}
Please add new line.

2022-04-10 18:15 UTC, arneschreuder commented
PR also still has conflicts. Remember to sync with upstream/develop.

2022-04-10 18:59 UTC, bevanslabbert commented
Thank you for the feedback!

2022-04-11 12:26 UTC, closed without merging