✨(ui): create Company-Explore directory and layout
COS-301/graduates pull request #490
Opened 2022-04-05 16:18 UTC by Thivesshj

created the company-explore library. and designed the desktop-layout with angular, angular-materials, and angular flex-layout to match the wire frame.

2022-04-06 11:51 UTC, arneschreuder commented
Please resolve conflicts.

2022-04-06 11:59 UTC, arneschreuder requested changes
This is exciting. Nice. A few small changes. Also. You need a routing module. Get this merged in and then add routing. Specifically: https://angular.io/guide/lazy-loading-ngmodules

2022-04-06 11:59 UTC, arneschreuder commented on apps/client/src/app/app.module.ts
> +    ClientShellFeatureModule,ClientCompanyExploreFeatureModule,
Please move this import to be imported by the Shell. The ShellFeatureModule should be the only thing imported by app.module.ts

2022-04-06 11:59 UTC, arneschreuder commented on libs/client/company-explore/feature/src/lib/company-explore-feature/company-explore-content/company-explore-card/company-explore-card.component.html
> +<mat-card class="card" fxLayout="column">
Just a comment. Nx has feature libs and UI libs. You have it correct. A feature component belongs in the feature lib as you have it. Try see if there is a need to make UI libs. UI Libs are reusable "dumb" components. These include like searchbars, dropdowns etc. Just a comment. No changes needed.

2022-04-06 11:59 UTC, arneschreuder commented on libs/client/company-explore/feature/src/lib/materials/company-explore-material.module.ts
> +import { NgModule } from '@angular/core';
Perhaps make a shared module and export/import all of these there. Like a MaterialShared Module or something. Then other people can also use it.

2022-04-08 08:47 UTC, Thivesshj commented on apps/client/src/app/app.module.ts
> +    ClientShellFeatureModule,ClientCompanyExploreFeatureModule,
removed import from the app.module.ts

2022-04-10 15:55 UTC, Thivesshj commented on libs/client/company-explore/feature/src/lib/materials/company-explore-material.module.ts
> +import { NgModule } from '@angular/core';
speaking to the person in charge of the shared libs, and will add it after my merge

2022-04-10 15:57 UTC, Thivesshj commented on libs/client/company-explore/feature/src/lib/company-explore-feature/company-explore-content/company-explore-card/company-explore-card.component.html
> +<mat-card class="card" fxLayout="column">
I will be sure to look into that. thank you.

2022-04-10 17:49 UTC, arneschreuder commented
I'm copy pasting this on all the open PRs. Ignore if already seen or applied: https://github.com/COS-301/graduates/discussions/3?sort=new#discussioncomment-2540319

2022-04-10 18:00 UTC, arneschreuder commented
This PR still needs to update with `upstream/develop`

2022-04-10 19:08 UTC, Thivesshj commented
I updated my PR and my branch is now up to date with the upstream COS-301:develop .Thank you :sparkles::thumbsup::sparkles:

2022-04-10 19:51 UTC, arneschreuder approved these changes

2022-04-11 10:09 UTC, merged