:sparkles: (libs): UI Kit Cards Component
COS-301/graduates pull request #518
Opened 2022-04-10 20:20 UTC by MatthewRobinMarsden

The angular implementation of the cards component. This component is part of the general UI Kit library created by the UI Kit team. Architecture team @COS-301/visual-basic.

2022-04-10 20:44 UTC, JurassicRegz commented
Everything is good, fix should release tomorrow for making sure that the same meta test runs when changing labels inside the PR.

2022-04-10 20:52 UTC, evilcomrade commented
> Everything is good, fix should release tomorrow for making sure that the same meta test runs when changing labels inside the PR.

Awesome thanks for the speedy assistance :D

2022-04-11 13:44 UTC, arneschreuder requested changes
Please generate the libs using the correct tooling. This is what I was talking about in class today :)

Also, I suggest making this PR again from your feature branch and not from your own develop. So git checkout -b feature/my-branch and then make the PR from there.

2022-04-11 13:44 UTC, arneschreuder commented on libs/client/shared/components/cards/ui/README.md
> +This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 13.3.1.
No, please generate libraries using `nx` not using `ng`. Use the VSCode NX console extension and use `nrwl/angular library`

2022-04-11 15:35 UTC, closed without merging