🚧(ui): Adding API service, integrating NGXS
COS-301/graduates pull request #576
Opened 2022-04-11 18:38 UTC by dylan2894

- Added a service that consumes the request-for-access API. 
- Integrated the NGXS state management with the request-for-access API calls. 
- Finished responsive styling. 
- Optimised HTML.

2022-04-11 19:42 UTC, arulagrawal submitted a review, later dismissed

2022-04-12 11:45 UTC, arneschreuder requested changes
Not a bad PR. Some convention stuff that should be followed.

2022-04-12 11:45 UTC, arneschreuder commented on libs/client/request-for-access/feature/src/lib/request-for-access.actions.ts
> +export class SetAccessStatus {
This is fine for now. But consider putting actions in its own folder.

2022-04-12 11:45 UTC, arneschreuder commented on libs/client/request-for-access/feature/src/lib/request-for-access.component.ts
> +      this.apiService.getResourceStatuses('4', '2').subscribe({
Technically speaking, this part need to be in a NGXS Store. But I will accept this for now. Has to be changed in the future though.

2022-04-12 11:45 UTC, arneschreuder commented on libs/client/request-for-access/feature/src/lib/request-for-access.component.ts
> +          while(response.data.status[i] != undefined) {
While loops are always scary. Can we not do this differently?

2022-04-12 11:45 UTC, arneschreuder commented on libs/client/request-for-access/feature/src/lib/request-for-access.module.ts
> +    NgxsModule.forRoot([
This should not be forRoot. Should be forFeature. If you want to add the store to the "global" scope. Then the store should be configured in the shell's module.

2022-04-12 11:45 UTC, arneschreuder commented on libs/client/request-for-access/feature/src/lib/request-for-access.state.ts
> +import { SetAccessStatus } from './request-for-access.actions';
Convention is to put states in a stores folder.

2022-04-12 11:45 UTC, arneschreuder commented on libs/client/request-for-access/feature/src/lib/services/request-for-access.service.ts
> +      return ajax({
Why Ajax? Angular has a built in httpClient that makes this SO much easier. Please change out.

2022-04-12 13:09 UTC, dylan2894 commented
@arneschreuder Should the actions folder and stores folder be nested inside the lib folder? (as it is now with my new commits)

2022-04-12 13:21 UTC, arneschreuder commented on libs/client/request-for-access/feature/src/lib/services/request-for-access.service.ts
> +      return ajax({
How is this resolved?

2022-04-12 13:23 UTC, arneschreuder approved these changes
Good stuff. Thanks

2022-04-12 13:23 UTC, arneschreuder commented
Go ahead and merge!

2022-04-12 13:46 UTC, merged