🛂 🔥 (repo) Added repository data-access,needs tests,remove unneeded files
COS-301/graduates pull request #710
Opened 2022-04-14 07:31 UTC by Ray-net

2022-04-14 08:25 UTC, Vhulenda88 requested changes
Just change your tests to the way I described above

2022-04-14 08:25 UTC, Vhulenda88 commented on libs/api/authorization/repository/data-access/src/lib/api-authorization-repository-admin.spec.ts
> +test('company check company story', async () => {
Your unit tests need to have
```
 describe('your test function', () => {
    it('some text',
        () => {
               expect(the function you are testing).toBe(call);
        });
```

2022-04-14 09:09 UTC, Ray-net commented on libs/api/authorization/repository/data-access/src/lib/api-authorization-repository-admin.spec.ts
> +test('company check company story', async () => {
Cool. I am busy doing it like that

2022-04-15 13:20 UTC, Vhulenda88 approved these changes

2022-04-15 14:21 UTC, merged