:ok_hand: (request-for-access): changed to status resolver
COS-301/graduates pull request #859
Opened 2022-04-16 13:37 UTC by MichaelDuPlessis

If an item has not been requested than it is still returned in status as private

2022-04-16 14:06 UTC, arulagrawal requested changes

2022-04-16 14:06 UTC, arulagrawal commented on libs/api/access-status/api/feature/src/lib/api-access-status.resolver.ts
> +        const items = ["CV", "Transcript", "Academic Record", "Certificates", "Capstone Project"];
We should probably be using the enum here as well.

2022-04-16 14:44 UTC, MichaelDuPlessis commented on libs/api/access-status/api/feature/src/lib/api-access-status.resolver.ts
> +        const items = ["CV", "Transcript", "Academic Record", "Certificates", "Capstone Project"];
In all honesty it just makes the code unnecessarily more complex but since there are breaks i other peoples code I shall keep looking.

2022-04-16 15:29 UTC, arulagrawal commented on libs/api/access-status/api/feature/src/lib/api-access-status.resolver.ts
> +        const items = ["CV", "Transcript", "Academic Record", "Certificates", "Capstone Project"];
Well we should either use it everywhere or not at all. We should remove it from the other file if you feel its unnecessary complexity

2022-04-16 18:44 UTC, arulagrawal commented on libs/api/access-status/api/feature/src/lib/api-access-status.resolver.ts
> +        const items = ["CV", "Transcript", "Academic Record", "Certificates", "Capstone Project"];
@MichaelDuPlessis do you want to leave this as is for now?

2022-04-16 18:45 UTC, MichaelDuPlessis commented on libs/api/access-status/api/feature/src/lib/api-access-status.resolver.ts
> +        const items = ["CV", "Transcript", "Academic Record", "Certificates", "Capstone Project"];
I am trying to get it to work with enums if it's I don't by tomorrow morning let's leave it

2022-04-17 09:44 UTC, MichaelDuPlessis commented on libs/api/access-status/api/feature/src/lib/api-access-status.resolver.ts
> +        const items = ["CV", "Transcript", "Academic Record", "Certificates", "Capstone Project"];
I think for now lets leave it like this so Dylan can work with it

2022-04-17 13:01 UTC, arulagrawal approved these changes

2022-04-17 13:02 UTC, merged