✨ Authorization Service Layer Handlers feature
COS-301/graduates pull request #954
Opened 2022-04-17 14:46 UTC by Khotso-Bore

The service layer and it's accompanying Queries and handler functions have been completed. closed

2022-04-17 14:54 UTC, Ray-net commented
Cant merge untill the linting and the build part are fixed

2022-04-17 14:55 UTC, Ray-net commented
You need to resolve the error in the build test

2022-04-17 15:13 UTC, Ray-net commented
Went from 5 errors to 2 almost there

2022-04-17 15:21 UTC, Ray-net commented
Looks like a problem in the company explore

2022-04-17 15:21 UTC, Ray-net commented
Might want to let then know in group chat

2022-04-17 15:21 UTC, Ray-net commented
Cant commit till their work is fixed

2022-04-17 15:27 UTC, Khotso-Bore commented
yeah, I was gonna suggest I wait till they put up a new PR before I try again

2022-04-17 15:36 UTC, Ray-net commented
create test for api-authorization-api-feature:test
and api-authorization-service-feature:test

2022-04-17 18:35 UTC, Ray-net commented
I will add the last test you figure out the linting problem

2022-04-17 18:54 UTC, Khotso-Bore commented
i got the last test working
I just don't get the linting

2022-04-17 19:01 UTC, Ray-net commented
Does one of you functions have a chance of returning undefined

2022-04-17 19:01 UTC, Ray-net commented
If it does change it to return null

2022-04-17 19:11 UTC, Khotso-Bore commented
none of them return anything undefined as far as i'm concerned

2022-04-17 19:17 UTC, Vhulenda88 commented
@arneschreuder, may you please assist us with the lint test failing, we are unaware of how to fix it

2022-04-18 04:32 UTC, arneschreuder requested changes
Please fix imports, then resubmit for review. Also, please do not make the PR from your development branch, please make it from a feature branch. It makes PRs a bit difficult

2022-04-18 04:32 UTC, arneschreuder commented on libs/api/authorization/api/feature/src/lib/api-authorization-api-feature.module.ts
> +// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
Please remove and import correctly using @graduates/whatever notation. If this doesnt work. Your lib was not created correctly

2022-04-18 04:32 UTC, arneschreuder commented on libs/api/authorization/api/feature/src/lib/api-authorization-api-feature.module.ts
> +import { ApiAuthorization } from '../../../shared/src/lib/api-authorization.entity';
Please import correctly. Use @graduates/whatever notation

2022-04-18 04:32 UTC, arneschreuder commented on libs/api/authorization/api/feature/src/lib/api-authorization-api-feature.module.ts
> +  providers: [ApiAuthorizationResolver, ApiAuthorization],
I can’t remember that you have to provide entities. Please double check, but I think this is wrong

2022-04-18 04:32 UTC, arneschreuder commented on libs/api/authorization/api/feature/src/lib/api-authorization.resolver.spec.ts
> +import { ApiAuthorizationService } from '@graduates/api/authorization/service/feature';
This is wrong

2022-04-18 06:56 UTC, closed without merging